### ISSUE TITLE
Unauthorized after updating library dependency

### ISSUE THREAD

**Issue by Ziocash** [fattureincloud/fattureincloud-csharp-sdk#103]
**Describe the bug**
- Using `IssuedDocumentsApi` async methods return Unauthorized
- Using `IssuedDocumentsApi` sync methods throw RestSharp RestClientSyncExtensions cannot be loaded

**Env info**
- C# 11
- C# SDK 2.1.0

**To Reproduce**
- Example code:
```cs
var client = new IssuedDocumentsApi(_configuration);
var response = await client.ListIssuedDocumentsAsync(_options.CompanyId, "invoice");
return response;
```
- Error status and message:
401 - Unauthorized
- Stacktrace:
```
It.FattureInCloud.Sdk.Client.ApiException: Error calling ListIssuedDocuments: {"error":{"message":"Unauthorized."}}
   at It.FattureInCloud.Sdk.Api.IssuedDocumentsApi.ListIssuedDocumentsWithHttpInfoAsync(Int32 companyId, String type, String fields, String fieldset, String sort, Nullable`1 page, Nullable`1 perPage, String q, Nullable`1 inclusive, Int32 operationIndex, CancellationToken cancellationToken)
   at It.FattureInCloud.Sdk.Api.IssuedDocumentsApi.ListIssuedDocumentsAsync(Int32 companyId, String type, String fields, String fieldset, String sort, Nullable`1 page, Nullable`1 perPage, String q, Nullable`1 inclusive, Int32 operationIndex, CancellationToken cancellationToken)
```
- JSON representation of the request body
```json
{"error":{"message":"Unauthorized."}}
```

**Expected behavior**
A list of issued documents from the called method

**Screenshots**
No screenshot

**Additional context**
RestSharp update to the latest version (112.1.0) to avoid [GHSA-4rr6-2v9v-wcpc](https://github.com/advisories/GHSA-4rr6-2v9v-wcpc)

**Comment by barcigabri** [comment]
Hello, I just tried it myself with dotnet 7.0 and sdk version 2.1.1 and it's working as expected, do you get this error even with the last version of the sdk? If you till get it, send us the full error message and we will inspect it

**Comment by Ziocash** [comment]
Updated SDK to 2.1.1 and not working
- [x] Tried in .NET 8 and overrided RestSharp (v.112.1.0) and not working
- [x] Tried in .NET 8 without RestSharp as a locally-installed package and not working
Same error as I previously written down, maybe could be something in the configuration class.

How did you configured the client? 
I can check if there are some mismatches between mine and yours

**Comment by valmoz** [comment]
Hi @Ziocash 
can you please share your configuration (with omitted token)?
I expect it to be something like: 

```cs
Configuration config = new Configuration();
 // Configure OAuth2 access token for authorization: OAuth2AuthenticationCodeFlow
config.AccessToken = "YOUR_ACCESS_TOKEN";
```

Thanks 
Mauro

**Comment by Ziocash** [comment]
Hi @valmoz,
here it is
```cs
public FattureInCloudInvoiceService(ILogger<FattureInCloudInvoiceService> logger, IOptions<FattureInCloudInvoiceServiceOptions> options)
{
    _logger = logger;
    _options = options.Value;
    _configuration = new()
    {
        AccessToken = _options.Token
    };
    GetCountries();
}
```

I'm currently building a service for a web application, so `options` are already populated by caller, Token is correct and is equal to the one provided by the website

**Comment by Ziocash** [comment]
Hello @valmoz,

I'm trying to list issued documents by type = invoice
![image](https://github.com/user-attachments/assets/eeee6608-3ce5-44d3-bc7d-d688be9cb8be)
AccessToken and CompanyId have both a value (same value as Postman) so I think it's a kind of issue somewhere else

**Comment by valmoz** [comment]
Hi @Ziocash 
no problem, we're glad you were able to solve this issue.

Thanks
Mauro
