### ISSUE TITLE
Installazione via Nuget

### ISSUE THREAD

**Issue by federico-66** [fattureincloud/fattureincloud-csharp-sdk#42]
Salve,
sto cercando di installare SDK via Nuget, ma ricevo sempre il segunete errore:
**Non è stato possibile installare il pacchetto 'It.FattureInCloud.Sdk 2.0.8'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.6.2', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.**

Ho provato anche ad installare da console prima le dipendenze (minime) e poi l'sdk
**Install-Package It.FattureInCloud.Sdk -Version 2.0.8 -IgnoreDependencies**
ma il risultato è lo stesso:

Install-Package : Non è stato possibile installare il pacchetto 'It.FattureInCloud.Sdk 2.0.8'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.6.2', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.
In riga:1 car:16
+ Install-Package <<<<  It.FattureInCloud.Sdk -Version 2.0.8 -IgnoreDependencies
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand**

Grazie
Federico

**Comment by emajo** [comment]
Ciao Federico, ho appena fatto un test creando un progetto che utilizza il .NETFramework 4.6.2 e l'installazione dell'SDK va a buon fine, quello che ti chiederei di fare è provare un altro metodo d'installazione, o utilizzando direttamente lo store di nuget da Visual Studio oppure aggiungendo la dipendenza manualmente al progetto.

In caso nulla di ciò funzionasse ti chiederei di provare ad installare la nostra SDK su un nuovo progetto completamente vuoto, per assicurarci del fatto che il problema non sia relativo a dei conflitti tra le dipendenze già presenti nel tuo progetto.

Grazie,
Emanuele

**Comment by federico-66** [comment]
Ciao Emanuele,
credo di aver risolto. Ho installato prima le dipendenze:
Install-Package RestSharp -Version 106.13.0
Install-Package Newtonsoft.Json –Version 13.0.1
Install-Package JsonSubTypes –Version 1.8.0
Install-Package System.ComponentModel.Annotations –Version 5.0.0
Install-Package Polly –Version 7.2.3
e poi, dopo aver scaricato il pacchetto nuget It.FattureInCloud.Sdk, ho referenziato manualmente la dll.
Sto facendo qualche test e sembra ok.
Purtroppo sto usando VS2013 e so di qualche problema con il package manager, forse il problema è dovuto a quello.
Appena mi è possibile farò qualche altra prova con versioni più aggiornate di VS :-)

Grazie
Federico
