### ISSUE TITLE
Errore di conversione in json per gli oggetti anonimi associati ai campi custom della fatturazione elettronica

### ISSUE THREAD

**Issue by Duavide** [fattureincloud/fattureincloud-csharp-sdk#56]
Buongiorno.
Penso di aver trovato un problema di conversione in json che si verifica vengono compilati i campi custom associati alla fatturazione elettronica nei vari modelli di questa libreria.
Il bug che ho rilevato avviene durante la conversione in json di oggetti che contengono proprietà di tipo object da utilizzare con oggetti anonimi. Un esempio è la proprietà **EiRaw** nella classe **It.FattureInCloud.Sdk.Model.IssuedDocument**. 
Il problema si verifica ad esempio se creo un oggetto di tipo **It.FattureInCloud.Sdk.Model.CreateIssuedDocumentResponse** per la creazione di una fattura e compilo il campo EiRaw dentro Data nel seguente modo:
```c#
request.Data.EiRaw = new
{
    FatturaElettronicaBody = new
    {
        DatiGenerali = new
        {
            DatiDDT = new[] {
                new
                {
                    NumeroDDT = "Fatt1",
                    DataDDT = "2022-01-01",
                },
                new
                {
                    NumeroDDT = "Fatt2",
                    DataDDT = "2022-02-02",
                },
            }
        },

    }
};
```
Quando chiamerò la Create Issued Document, l'oggetto della richiesta verrà convertito in json correttamente tranne che per il campo EiRaw che verrà convertito nel seguente modo:
```json
 "ei_raw": {
        "fatturaElettronicaBody": {
          "datiGenerali": {
            "datiDDT": [
              {
                "numeroDDT": "Fatt1",
                "dataDDT": "2022-01-01"
              },
              {
                "numeroDDT": "Fatt2",
                "dataDDT": "2022-02-02"
              }
            ]
          }
        }
      }
```
Il salvataggio e la creazione avvengono con successo anche se si porterà dietro l'errata conversione in json delle lettere iniziali dei nodi che fanno riferimento al tracciato xml. Infatti il problema è la conversione standard delle iniziali dei nomi da maiuscole a minuscole.
A questo punto chiamando la GetIssuedDocument il campo ei_raw conterrà i nodi dentro ei_raw coi nomi in minuscolo.
La problematica è che il sistema si aspetta dei nomi esattamente uguali al tracciato XML della fattura elettronica. Infatti aprendo il documento nell'interfaccia grafica di FattureInCloud, i dati inviati non compariranno perché non conformi e quindi ignorati.

Per risolvere il bug bisognerebbe fare in modo che gli oggetti anonimi passati a proprietà come **EiRaw** vengano convertiti mantenendo le le maiuscole iniziali come nel seguente modo:
```json
 "ei_raw": {
        "FatturaElettronicaBody": {
          "DatiGenerali": {
            "DatiDDT": [
              {
                "NumeroDDT": "Fatt1",
                "DataDDT": "2022-01-01"
              },
              {
                "NumeroDDT": "Fatt2",
                "DataDDT": "2022-02-02"
              }
            ]
          }
        }
      }
```
Purtroppo questo è un bug abbastanza importante perché impedisce la compilazione dei campi custom dei documenti elettronici tramite il vostro servizio C#. 
Vi ringrazio e vi auguro un buon lavoro.

**Comment by emajo** [comment]
Ciao davide,
innanzitutto ti ringrazio per la segnalazione, effettivamente è un bug abbastanza importante di cui non eravamo a conoscenza, abbiamo già pronto il fix che sarà incluso nel prossimo rilascio che probabilmente avverrà nel giro di 1-2 settimane.
Intanto grazie per la pazienza, ti avviseremo non appena sarà fuori la nuova versione.

**Comment by emajo** [comment]
Ciao Davide, la nuova versione dell'sdk che risolve il bug da te riportato è stata rilasciata ieri ([2.0.10](https://www.nuget.org/packages/It.FattureInCloud.Sdk)), in caso si ripresentasse il problema o ne trovassi degli altri, sentiti libero di aprire un altra issue o di scrivere un post sulla nostra [community](https://developers.fattureincloud.it/discuss).

Grazie,
Emanuele
