### ISSUE TITLE
Errore durante chiamata Api "Method not found: Void RestSharp.RestRequest..ctor(RestSharp.Method)"

### ISSUE THREAD

**Issue by draedr** [fattureincloud/fattureincloud-csharp-sdk#57]
Buongiorno.
Ogni volta che provo ad eseguire una chiamata alle api, ottengo come exception "Method not found: Void RestSharp.RestRequest..ctor(RestSharp.Method)", senza stacktrace oltre a questo errore.
Ho avuto questo problema facendo le seguenti chiamate:
- IssuedDocumentsApi.ListIssuedDocumentsAsync
- IssuedDocumentsApi.CreateIssuedDocumentWithHttpInfo
- IssuedDocumentsApi.CreateIssuedDocumentWithHttpInfoAsync

Al momento, ho provato a:
- Reinstallare l'sdk
- Downgrade dell'sdk
- Downgrade di RestSharp

**Comment by emajo** [comment]
Closed [here](https://developers.fattureincloud.it/discuss/6299ba74e7ed1f001472c29a)
