### ISSUE TITLE
Get Issued Document Pre-create info

### ISSUE THREAD

**Issue by aserra1984** [fattureincloud/fattureincloud-csharp-sdk#60]
Hello, 

I used the SDK to perform various operations on my account such as creating or retrieving an invoice. 

When I use this GetIssuedDocumentPreCreateInfo method to retrieve data in IssuedDocumentsApi I have null as an answer, if I look at the logs in the portal the status is 200. 

If I try to make the call from the API reference page I have results?

![image](https://user-images.githubusercontent.com/53299728/177997151-7d3d9649-3479-47ec-b632-9f0265c4770d.png)

Thanks,
A

**Comment by emajo** [comment]
Hi, I tried to use the same method and it works as expected, maybe you are not using the last version of the sdk, you can check [here](https://www.nuget.org/packages/It.FattureInCloud.Sdk), let us know if it solves your issue,

Thanks,
Emanuele
