### ISSUE TITLE
Scope issued_documents.work_reports is not present in "Enum Scope" of the It.FattureInCloud.Sdk.OauthHelper

### ISSUE THREAD

**Issue by addsac** [fattureincloud/fattureincloud-csharp-sdk#64]
Salve, sto cercando di creare un documento 'rapportino di lavoro' tramite api v2, ma negli scope da aggiungere prima di avere il token non è presente "issued_documents.work_reports" nella classe Scope.

E' possibile sapere se sarà aggiunto "issued_documents.work_reports"?

grazie

**Comment by emajo** [comment]
Ciao @addsac abbiamo appena rilasciato la nuova versione dell'sdk in cui troverai tutti gli scope che ti servono.

Grazie per la segnalazione,
Emanuele

**Comment by addsac** [comment]
Provato e funziona, grazie mille per la velocità! 👍🏻

**Comment by addsac** [comment]
Ciao @emajo , da quando abbiamo aggiornato il pacchetto nudget ad ogni tentata chiamata api mi da un errore di char-utf8. Sai per caso se è un problema di configurazione nostra o se lerrore è nell'sdk? 

allego la foto, grazie per la pazienza. 

![IMG_0879](https://user-images.githubusercontent.com/62037079/191907944-ef411dd7-7e6a-471f-a146-ef2b2222be17.png)

**Comment by valmoz** [comment]
Ciao @addsac 
sembrerebbe essere un problema legato a [questa issue](https://github.com/dotnet/runtime/issues/20272).
Questo comando probabilmente viene utilizzato all'interno di RestSharp, e quindi si ottiene questo errore.

Il problema probabilmente sorge a riga 370 di ApiClient.cs, dove viene settato l'header con quel valore.
Cercheremo di capire se è possibile aggirare il problema tramite configurazione dell'SDK o se sarà necessario generarne una nuova versione senza quell'istruzione.

Grazie
Mauro

**Comment by addsac** [comment]
Ok, grazie. quindi mi conviene aspettare che risolvete (senza fretta naturalmente) o cercare di aggirare il problema da solo? grazie

**Comment by emajo** [comment]
Ciao @addsac, innanzitutto ci scusiamo per il disguido, abbiamo rilasciato una nuova versione ora che sistema questo problema (2.0.14), se ci sono altri problemi rimaniamo a disposizione.

Grazie,
Emanuele.

**Comment by emajo** [comment]
Ciao @addsac grazie ancora per la segnalazione, ti chiedo di provare ad aggiornare ora e fare un test, dovrebbe andare.

**Comment by addsac** [comment]
Perfetto, ora funziona grazie per la velocità!

**Comment by valmoz** [comment]
Perfetto @addsac chiudiamo la issue.
Per favore, se hai altri problemi con l'SDK ricordati di creare issues separate se il problema non è correlato.

Grazie
Mauro
