### ISSUE TITLE
Impostare una property di un modello a null fa fallire la chiamata

### ISSUE THREAD

**Issue by bellamatte** [fattureincloud/fattureincloud-csharp-sdk#73]
**Describe the bug**
Se imposto una property di un modello a null, questo può far fallire la chiamata in quanto la property, anche se impostata a null, viene flaggata come "da serializzare" e inclusa quindi nella chiamata.
Il server poi non accetta il valore di questa property e ritorna un errore di validazione.

**To Reproduce**
Per chiamare la `CreateIssuedDocumentAsync`, compilo la Entity in base ai dati che ho sul mio DB.
Provo a compilare tutti i dati, ma alcuni non sono presenti sul mio DB (Fax, VatNumber, TaxCode), poiché quello specifico cliente non li ha compilati.
Il codice quindi imposta Fax, VatNumber e TaxCode a null.
La chiamata `CreateIssuedDocumentAsync` ritorna il seguente errore:
422
```
{
    "error": {
        "message": "Invalid request.",
        "validation_result": {
            "data.entity.vat_number": ["The data.entity.vat number must be a string."],
            "data.entity.tax_code": ["The data.entity.tax code must be a string."],
            "data.entity.fax": ["The data.entity.fax must be a string."]
        }
    }
}
```

**Expected behavior**
Se imposto il valore a null, questo non dovrebbe essere considerato e non deve essere serializzato se il server non lo accetta.

**Comment by emajo** [comment]
Ciao @bellamatte, i campi in questione non vengono serializzati se non vengono settati specificatamente, il mio consiglio è quello di passare stringa vuota al posto di null oppure non settarli proprio, sarebbe utile escludere i campi null dalla serializzazione ma non è una modifica che pianifichiamo di fare a breve.

Grazie,
Emanuele.
